package com.tynan.taskmaster.taskmaster.Model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.util.Optional;
import java.util.UUID;


@DynamoDBTable(tableName = "taskmaster")
public class Task {
    private String id;
    private String title;
    private String description;
    private String status;
    private String assignee;
    private String image;

    public Task() {}

    public Task(String title, String description, Optional<String> assignee) {
        this.title = title;
        this.description = description;

        if (assignee.isPresent()) {
            this.assignee = assignee.get();
            this.status = "Assigned";
        } else {
            this.assignee = "NOT ASSIGNED";
            this.status = "Available";
        }
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBAttribute
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @DynamoDBAttribute
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @DynamoDBAttribute
    public String getAssignee() {
        return assignee;
    }

    public void setAssignee(String assignee) {
        this.assignee = assignee;
    }

    @DynamoDBAttribute
    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }
}
